- name: Update repositories cache and install docker dependencies
  ansible.builtin.apt:
    name:
      - python3-pip
      - docker.io
    update_cache: yes
    state: latest

- name: Install docker-compose python package
  ansible.builtin.pip:
    name: docker-compose
